# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión libre'), ('separado', 'Separado/a'), ('viudo', 'Viudo/a')], max_length=30, verbose_name='Estado civil')),
                ('profesion', models.CharField(blank=True, max_length=100, verbose_name='Profesión')),
                ('numero_hijos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de hijos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acudiente', to='personas.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'acudientes',
                'ordering': ['persona__primer_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico médico')),
                ('ultima_evolucion', models.TextField(blank=True, verbose_name='Última evolución clínica')),
                ('grado_escolar', models.CharField(blank=True, max_length=30, verbose_name='Grado escolar')),
                ('fecha_ingreso_hosp', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso al hospital')),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100, verbose_name='Lugar de nacimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to='personas.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiarios',
                'ordering': ['persona__primer_apellido'],
            },
        ),
        migrations.CreateModel(
            name='OcupacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualmente_trabaja', models.BooleanField(blank=True, null=True, verbose_name='¿Actualmente trabaja?')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=150, verbose_name='Lugar de trabajo')),
                ('horario_laboral', models.CharField(blank=True, max_length=100, verbose_name='Horario laboral')),
                ('actividad_desempenada', models.CharField(blank=True, max_length=150, verbose_name='Actividad desempeñada')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('independiente', 'Independiente'), ('contrato', 'Por contrato')], max_length=20, verbose_name='Tipo de contrato')),
                ('acudiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocupacion', to='beneficiarios.acudiente', verbose_name='Acudiente')),
            ],
            options={
                'verbose_name': 'Ocupación laboral',
                'verbose_name_plural': 'Ocupaciones laborales',
                'db_table': 'ocupacion_laboral',
            },
        ),
        migrations.CreateModel(
            name='AcudienteBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hermano', 'Hermano/a'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('otro', 'Otro')], max_length=60, verbose_name='Parentesco')),
                ('es_acudiente_principal', models.BooleanField(default=False, verbose_name='¿Es acudiente principal?')),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='beneficiarios.acudiente', verbose_name='Acudiente')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='beneficiarios.beneficiario', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Relación Acudiente-Beneficiario',
                'verbose_name_plural': 'Relaciones Acudiente-Beneficiario',
                'db_table': 'acudiente_beneficiario',
                'unique_together': {('acudiente', 'beneficiario')},
            },
        ),
    ]
