# Generated by Django 6.0.4 on 2026-04-29 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_donante', models.CharField(choices=[('persona_natural', 'Persona natural'), ('empresa', 'Empresa / Persona jurídica')], max_length=20, verbose_name='Tipo de donante')),
                ('nombre_empresa', models.CharField(blank=True, max_length=150, verbose_name='Nombre de la empresa')),
                ('nit', models.CharField(blank=True, max_length=25, verbose_name='NIT')),
                ('representante', models.CharField(blank=True, max_length=160, verbose_name='Representante legal')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('ciudad', models.CharField(blank=True, max_length=80, verbose_name='Ciudad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_registro', models.DateField(blank=True, null=True, verbose_name='Fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donante', to='personas.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Donante',
                'verbose_name_plural': 'Donantes',
                'db_table': 'donantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_donacion', models.CharField(choices=[('dinero', 'Dinero'), ('alimentos', 'Alimentos'), ('ropa', 'Ropa'), ('servicios', 'Servicios'), ('medicamentos', 'Medicamentos'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de donación')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para donaciones en dinero', max_digits=14, null=True, verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la donación en especie', verbose_name='Descripción')),
                ('fecha_donacion', models.DateField(verbose_name='Fecha de donación')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='donaciones/comprobantes/', verbose_name='Comprobante')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('procesada', 'Procesada'), ('asignada', 'Asignada')], default='recibida', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='proyectos.proyecto', verbose_name='Proyecto asociado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='donantes.donante', verbose_name='Donante')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donaciones',
                'ordering': ['-fecha_donacion'],
            },
        ),
    ]
