# Generated by Django 6.0.4 on 2026-04-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='tipo_donacion',
            field=models.CharField(choices=[('dinero', 'Dinero'), ('alimentos', 'Alimentos'), ('ropa', 'Ropa'), ('libros', 'Libros'), ('elementos_aseo', 'Elementos de aseo'), ('servicios', 'Servicios'), ('medicamentos', 'Medicamentos'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de donación'),
        ),
    ]
