# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donantes', '0002_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='donante',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donante', to='personas.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='donantes.donante', verbose_name='Donante'),
        ),
    ]
