# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del programa')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('beneficios', models.TextField(blank=True, verbose_name='Beneficios')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField(verbose_name='Fecha de seguimiento')),
                ('tipo_seguimiento', models.CharField(choices=[('visita', 'Visita domiciliaria'), ('llamada', 'Llamada telefónica'), ('sesion', 'Sesión presencial'), ('evaluacion', 'Evaluación'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de seguimiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'seguimientos',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(verbose_name='Fecha de inscripción')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('egresado', 'Egresado')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_egreso', models.DateField(blank=True, null=True, verbose_name='Fecha de egreso')),
                ('motivo_egreso', models.TextField(blank=True, verbose_name='Motivo de egreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='beneficiarios.beneficiario', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Inscripción a programa',
                'verbose_name_plural': 'Inscripciones a programas',
                'db_table': 'inscripciones_programas',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
