# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('programas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionprograma',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='inscripcionprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='programas.programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='beneficiarios.beneficiario', verbose_name='Beneficiario'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='programas.programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionprograma',
            unique_together={('beneficiario', 'programa')},
        ),
    ]
