# Generated by Django 6.0.4 on 2026-05-21 22:18

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subject', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('BUILDER', 'Editor'), ('IMAGE', 'Imagen'), ('PDF', 'PDF')], default='IMAGE', max_length=16)),
                ('html_content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='campaigns/docs/')),
                ('cta_text', models.CharField(blank=True, default='', max_length=64)),
                ('cta_url', models.URLField(blank=True, default='')),
                ('recipient_group', models.CharField(choices=[('DONORS', 'Donantes'), ('GUARDIANS', 'Acudientes'), ('USERS', 'Usuarios'), ('ALL', 'Todos')], default='DONORS', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENDING', 'Enviando'), ('SENT', 'Enviada'), ('FAILED', 'Fallida')], default='DRAFT', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'ordering': ['-id'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCampaign',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subject', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('BUILDER', 'Editor'), ('IMAGE', 'Imagen'), ('PDF', 'PDF')], default='IMAGE', max_length=16)),
                ('html_content', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('document', models.TextField(blank=True, max_length=100, null=True)),
                ('cta_text', models.CharField(blank=True, default='', max_length=64)),
                ('cta_url', models.URLField(blank=True, default='')),
                ('recipient_group', models.CharField(choices=[('DONORS', 'Donantes'), ('GUARDIANS', 'Acudientes'), ('USERS', 'Usuarios'), ('ALL', 'Todos')], default='DONORS', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENDING', 'Enviando'), ('SENT', 'Enviada'), ('FAILED', 'Fallida')], default='DRAFT', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Campaign',
                'verbose_name_plural': 'historical Campaigns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
