# Generated by Django 6.0.4 on 2026-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='recipient_group',
            field=models.CharField(choices=[('DONORS', 'Donantes'), ('GUARDIANS', 'Cuidadores'), ('USERS', 'Usuarios'), ('ALL', 'Todos')], default='DONORS', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalcampaign',
            name='recipient_group',
            field=models.CharField(choices=[('DONORS', 'Donantes'), ('GUARDIANS', 'Cuidadores'), ('USERS', 'Usuarios'), ('ALL', 'Todos')], default='DONORS', max_length=16),
        ),
    ]
