# Generated by Django 6.0.4 on 2026-05-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='design_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalcampaign',
            name='design_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
