# Generated by Django 6.0.4 on 2026-05-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_recipient_group_and_more'),
        ('campaigns', '0003_campaigntemplate_historicalcampaigntemplate'),
    ]

    operations = [
    ]
