# Generated by Django 6.0.4 on 2026-06-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_merge_20260529_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='recipient_group',
            field=models.CharField(choices=[('DONORS', 'Donantes'), ('GUARDIANS', 'Cuidadores'), ('USERS', 'Usuarios'), ('NEWSLETTER', 'Suscriptores del boletín'), ('ALL', 'Todos')], default='DONORS', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalcampaign',
            name='recipient_group',
            field=models.CharField(choices=[('DONORS', 'Donantes'), ('GUARDIANS', 'Cuidadores'), ('USERS', 'Usuarios'), ('NEWSLETTER', 'Suscriptores del boletín'), ('ALL', 'Todos')], default='DONORS', max_length=16),
        ),
    ]
