# Generated by Django 6.0.4 on 2026-06-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_recipient_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-id'], 'permissions': [('send_campaign', 'Can send campaign')], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
    ]
