# Generated by Django 6.0.4 on 2026-06-06 01:09

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=140)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('UNSUBSCRIBED', 'Desuscrito')], db_index=True, default='ACTIVE', max_length=20)),
                ('origin', models.CharField(choices=[('BLOG', 'Blog'), ('HOME', 'Sitio web'), ('CAMPAIGN', 'Campaña'), ('ADMIN', 'Panel administrativo'), ('OTHER', 'Otro')], db_index=True, default='BLOG', max_length=32)),
                ('consent', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'verbose_name_plural': 'Newsletter subscribers',
                'db_table': 'newsletter_subscribers',
                'ordering': ['-subscribed_at', '-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalNewsletterSubscriber',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=140)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('UNSUBSCRIBED', 'Desuscrito')], db_index=True, default='ACTIVE', max_length=20)),
                ('origin', models.CharField(choices=[('BLOG', 'Blog'), ('HOME', 'Sitio web'), ('CAMPAIGN', 'Campaña'), ('ADMIN', 'Panel administrativo'), ('OTHER', 'Otro')], db_index=True, default='BLOG', max_length=32)),
                ('consent', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Newsletter subscriber',
                'verbose_name_plural': 'historical Newsletter subscribers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
