# Generated by Django 6.0.4 on 2026-06-07 00:01

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('instagram_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video / Reel'), ('CAROUSEL_ALBUM', 'Carrusel')], db_index=True, max_length=32)),
                ('media_url', models.URLField(blank=True, default='', max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('permalink', models.URLField(blank=True, default='', max_length=1000)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('children', models.JSONField(blank=True, default=list)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Instagram post',
                'verbose_name_plural': 'Instagram posts',
                'db_table': 'instagram_posts',
                'ordering': ['-timestamp', '-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInstagramPost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('instagram_id', models.CharField(db_index=True, max_length=128)),
                ('caption', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video / Reel'), ('CAROUSEL_ALBUM', 'Carrusel')], db_index=True, max_length=32)),
                ('media_url', models.URLField(blank=True, default='', max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('permalink', models.URLField(blank=True, default='', max_length=1000)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('children', models.JSONField(blank=True, default=list)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Instagram post',
                'verbose_name_plural': 'historical Instagram posts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
