# Generated by Django 6.0.4 on 2026-04-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name': 'Guardian', 'verbose_name_plural': 'Guardians'},
        ),
        migrations.AlterModelOptions(
            name='historicalbeneficiary',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Beneficiary', 'verbose_name_plural': 'historical Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='historicalguardian',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Guardian', 'verbose_name_plural': 'historical Guardians'},
        ),
        migrations.AlterModelTable(
            name='beneficiary',
            table='beneficiaries',
        ),
        migrations.AlterModelTable(
            name='guardian',
            table='guardians',
        ),
    ]
