# Generated by Django 6.0.4 on 2026-05-20 22:42

import beneficiaries.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_beneficiary_options_alter_guardian_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='authorization_doc',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=beneficiaries.models.generate_beneficiary_auth_path),
        ),
    ]
