# Generated by Django 6.0.4 on 2026-05-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_alter_beneficiary_authorization_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='follow_up_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='received_aid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='treatment_stage',
            field=models.CharField(choices=[('INITIAL_SUPPORT', 'Apoyo integral inicial'), ('MID_TREATMENT', 'Mitad de tratamiento'), ('SURVIVOR', 'Sobreviviente')], default='INITIAL_SUPPORT', max_length=32),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='treatment_status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalbeneficiary',
            name='follow_up_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalbeneficiary',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalbeneficiary',
            name='received_aid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalbeneficiary',
            name='treatment_stage',
            field=models.CharField(choices=[('INITIAL_SUPPORT', 'Apoyo integral inicial'), ('MID_TREATMENT', 'Mitad de tratamiento'), ('SURVIVOR', 'Sobreviviente')], default='INITIAL_SUPPORT', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalbeneficiary',
            name='treatment_status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
