# Generated by Django 6.0.4 on 2026-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('MICRO', 'Micro'), ('PEQUENA', 'Pequeña'), ('MEDIANA', 'Mediana'), ('GRANDE', 'Grande')], default='MICRO', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='economic_sector',
            field=models.CharField(choices=[('INDUSTRIAL', 'Industrial'), ('COMERCIAL', 'Comercial'), ('SERVICIOS', 'Servicios'), ('TECNOLOGIA', 'Tecnología'), ('FINANCIERO', 'Financiero'), ('EDUCACION', 'Educación'), ('CONSTRUCCION', 'Construcción'), ('SALUD', 'Salud'), ('OTRO', 'Otro')], default='OTRO', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalcollectionpoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollectionpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='company_size',
            field=models.CharField(choices=[('MICRO', 'Micro'), ('PEQUENA', 'Pequeña'), ('MEDIANA', 'Mediana'), ('GRANDE', 'Grande')], default='MICRO', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='economic_sector',
            field=models.CharField(choices=[('INDUSTRIAL', 'Industrial'), ('COMERCIAL', 'Comercial'), ('SERVICIOS', 'Servicios'), ('TECNOLOGIA', 'Tecnología'), ('FINANCIERO', 'Financiero'), ('EDUCACION', 'Educación'), ('CONSTRUCCION', 'Construcción'), ('SALUD', 'Salud'), ('OTRO', 'Otro')], default='OTRO', max_length=64),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('IN_ROUTE', 'En Ruta'), ('COLLECTED', 'Recolectada'), ('PROCESSED', 'Procesada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalcollectionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('IN_ROUTE', 'En Ruta'), ('COLLECTED', 'Recolectada'), ('PROCESSED', 'Procesada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=32),
        ),
    ]
