# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre completo')),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('parentesco', models.CharField(blank=True, max_length=60, verbose_name='Parentesco con el menor')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
            ],
            options={
                'verbose_name': 'Miembro de familia',
                'verbose_name_plural': 'Miembros de familia',
                'db_table': 'miembros_familia',
            },
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('tipo_vivienda', models.CharField(blank=True, choices=[('propia', 'Propia'), ('arriendo', 'En arriendo'), ('familiar', 'Familiar')], max_length=20, verbose_name='Tipo de vivienda')),
                ('zona_residencia', models.CharField(blank=True, choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=10, verbose_name='Zona de residencia')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('barrio', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('estrato', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Estrato socioeconómico')),
                ('grupo_afrocolombiano', models.BooleanField(default=False, verbose_name='Afrocolombiano')),
                ('grupo_indigena', models.BooleanField(default=False, verbose_name='Indígena')),
                ('grupo_lgbtq', models.BooleanField(default=False, verbose_name='LGBTQ+')),
                ('grupo_migrante', models.BooleanField(default=False, verbose_name='Migrante')),
                ('grupo_desplazado', models.BooleanField(default=False, verbose_name='Desplazado por la violencia')),
                ('grupo_rom', models.BooleanField(default=False, verbose_name='Rom')),
                ('grupo_otro', models.CharField(blank=True, max_length=100, verbose_name='Otro grupo poblacional')),
                ('tiene_eps', models.BooleanField(blank=True, null=True, verbose_name='¿Tiene EPS?')),
                ('nombre_eps', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la EPS')),
                ('tipo_eps', models.CharField(blank=True, choices=[('subsidiado', 'Subsidiado'), ('contributivo', 'Contributivo')], max_length=20, verbose_name='Tipo de EPS')),
                ('tiene_sisben', models.BooleanField(blank=True, null=True, verbose_name='¿Tiene SISBÉN?')),
                ('nivel_sisben', models.CharField(blank=True, max_length=10, verbose_name='Nivel SISBÉN')),
                ('tiene_caja_comp', models.BooleanField(blank=True, null=True, verbose_name='¿Tiene caja de compensación?')),
                ('nombre_caja_comp', models.CharField(blank=True, max_length=100, verbose_name='Caja de compensación')),
                ('servicio_luz', models.BooleanField(default=False, verbose_name='Luz')),
                ('servicio_agua', models.BooleanField(default=False, verbose_name='Agua')),
                ('servicio_gas', models.BooleanField(default=False, verbose_name='Gas')),
                ('servicio_television', models.BooleanField(default=False, verbose_name='Televisión')),
                ('servicio_internet', models.BooleanField(default=False, verbose_name='Internet')),
                ('tiene_transporte', models.BooleanField(default=False, verbose_name='¿Tiene medio de transporte?')),
                ('tipo_transporte', models.CharField(blank=True, max_length=80, verbose_name='Tipo de transporte')),
                ('convivientes_cantidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de convivientes')),
                ('ingreso_mensual_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingreso mensual familiar')),
                ('descripcion_relacion_fam', models.TextField(blank=True, verbose_name='Descripción de la relación familiar')),
                ('forma_suplir_alimentacion', models.TextField(blank=True, verbose_name='¿Cómo suple la alimentación?')),
                ('alimentos_comidas', models.TextField(blank=True, verbose_name='Alimentos en comidas')),
                ('nna_en_sistema_educativo', models.BooleanField(blank=True, null=True, verbose_name='¿NNA en sistema educativo?')),
                ('actividades_tiempo_libre', models.TextField(blank=True, verbose_name='Actividades en tiempo libre')),
                ('frecuencia_actividades', models.CharField(blank=True, max_length=80, verbose_name='Frecuencia de actividades')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizaciones', to='beneficiarios.acudiente', verbose_name='Acudiente')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizaciones', to='beneficiarios.beneficiario', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Caracterización',
                'verbose_name_plural': 'Caracterizaciones',
                'db_table': 'caracterizaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
