# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracterizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caracterizaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='miembrofamilia',
            name='caracterizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_familia', to='caracterizaciones.caracterizacion', verbose_name='Caracterización'),
        ),
    ]
