# Generated by Django 6.0.4 on 2026-04-29 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('acudiente', 'Acudiente'), ('beneficiario', 'Beneficiario'), ('donante', 'Donante'), ('staff', 'Staff'), ('voluntario', 'Voluntario')], max_length=25, verbose_name='Tipo de persona')),
                ('primer_nombre', models.CharField(max_length=80, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=80, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=80, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=80, verbose_name='Segundo apellido')),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('CE', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte'), ('NIT', 'NIT')], max_length=20, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Número de documento')),
                ('ciudad_exp_documento', models.CharField(blank=True, max_length=80, verbose_name='Ciudad de expedición')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('parentesco', models.CharField(blank=True, max_length=60, verbose_name='Parentesco')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='personas.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Contacto de emergencia',
                'verbose_name_plural': 'Contactos de emergencia',
                'db_table': 'contactos_emergencia',
            },
        ),
    ]
