# Generated by Django 6.0.4 on 2026-06-02 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('google_email', models.EmailField(blank=True, default='', max_length=254)),
                ('marketing_opt_in', models.BooleanField(default=True)),
                ('news_opt_in', models.BooleanField(default=True)),
                ('impact_opt_in', models.BooleanField(default=True)),
                ('data_processing_opt_in', models.BooleanField(default=False)),
                ('preferred_contact', models.CharField(blank=True, default='email', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account Profile',
                'verbose_name_plural': 'User Account Profiles',
                'db_table': 'user_account_profiles',
            },
        ),
    ]
