# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccountprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="accounts/profile_photos/"),
        ),
    ]
