# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_useraccountprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccountprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
