# Generated by Django 6.0.4 on 2026-04-29 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades', models.TextField(blank=True, help_text='Descripción libre de habilidades, profesión u oficio', verbose_name='Habilidades')),
                ('disponibilidad', models.CharField(choices=[('weekdays', 'Entre semana'), ('weekends', 'Fines de semana'), ('flexible', 'Flexible')], default='flexible', max_length=20, verbose_name='Disponibilidad horaria')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio como voluntario')),
                ('observaciones', models.TextField(blank=True, help_text='Notas del coordinador sobre el voluntario', verbose_name='Observaciones internas')),
                ('acepta_tratamiento_datos', models.BooleanField(default=False, help_text='Requerido por la Ley 1581 de 2012', verbose_name='Acepta tratamiento de datos personales')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación de términos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voluntario', to='personas.persona', verbose_name='Persona')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'db_table': 'voluntarios',
                'ordering': ['persona__primer_apellido', 'persona__primer_nombre'],
            },
        ),
    ]
