# Generated by Django 6.0.4 on 2026-04-29 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('donacion', 'Donación'), ('voluntario', 'Voluntario'), ('alianza', 'Alianza empresarial'), ('contacto', 'Contacto general')], max_length=20, verbose_name='Tipo de solicitud')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo — sin revisar'), ('en_proceso', 'En proceso'), ('atendido', 'Atendido'), ('descartado', 'Descartado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('tipo_donacion', models.CharField(blank=True, help_text='monetary | species — Completado si tipo=donacion', max_length=30, verbose_name='Tipo de donación')),
                ('monto_donacion', models.DecimalField(blank=True, decimal_places=2, help_text='Solo si tipo_donacion=monetary', max_digits=14, null=True, verbose_name='Monto de donación')),
                ('habilidades', models.TextField(blank=True, help_text='Completado si tipo=voluntario', verbose_name='Habilidades')),
                ('disponibilidad', models.CharField(blank=True, help_text='weekdays | weekends | flexible', max_length=20, verbose_name='Disponibilidad')),
                ('nombre_empresa', models.CharField(blank=True, max_length=150, verbose_name='Nombre de la empresa')),
                ('propuesta_alianza', models.TextField(blank=True, verbose_name='Propuesta de alianza')),
                ('acepta_tratamiento_datos', models.BooleanField(default=False, help_text='Requerido por la Ley 1581 de 2012', verbose_name='Acepta tratamiento de datos personales')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atención')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
            ],
            options={
                'verbose_name': 'Solicitud (Lead)',
                'verbose_name_plural': 'Solicitudes de la Landing Page',
                'db_table': 'formularios_leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
