# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('adulto', 'Adulto'), ('menor_edad', 'Menor de edad')], max_length=20, verbose_name='Tipo de consentimiento')),
                ('firmante_nombre', models.CharField(max_length=160, verbose_name='Nombre del firmante')),
                ('firmante_cedula', models.CharField(max_length=20, verbose_name='Cédula del firmante')),
                ('firmante_ciudad_exp', models.CharField(blank=True, max_length=80, verbose_name='Ciudad de expedición')),
                ('firmante_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del firmante')),
                ('firmante_es_rep_legal', models.BooleanField(default=False, verbose_name='¿Es representante legal?')),
                ('menor_nombre', models.CharField(blank=True, max_length=160, verbose_name='Nombre del menor')),
                ('menor_tipo_documento', models.CharField(blank=True, choices=[('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('CE', 'Cédula de Extranjería')], max_length=20, verbose_name='Tipo de documento del menor')),
                ('menor_numero_documento', models.CharField(blank=True, max_length=20, verbose_name='Número de documento del menor')),
                ('acepta_uso_imagen', models.BooleanField(default=False, verbose_name='Autoriza uso de imagen')),
                ('acepta_datos_sensibles', models.BooleanField(default=False, verbose_name='Autoriza datos sensibles')),
                ('acepta_publicacion_redes', models.BooleanField(default=False, verbose_name='Autoriza publicación en redes')),
                ('ciudad_firma', models.CharField(blank=True, max_length=80, verbose_name='Ciudad de firma')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de firma')),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='consentimientos/firmas/', verbose_name='Imagen de firma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acudiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='beneficiarios.acudiente', verbose_name='Acudiente')),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='beneficiarios.beneficiario', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Consentimiento informado',
                'verbose_name_plural': 'Consentimientos informados',
                'db_table': 'consentimientos',
                'ordering': ['-fecha_firma'],
            },
        ),
    ]
