# Generated by Django 6.0.4 on 2026-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('ECOAPORTE', 'Bono Donación / Ecoaporte'), ('PERMANENT_SPONSOR', 'Padrino Permanente')], default='ECOAPORTE', max_length=32),
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('PERSON', 'Persona natural'), ('FAMILY', 'Familia'), ('COMPANY', 'Empresa')], default='PERSON', max_length=16),
        ),
        migrations.AddField(
            model_name='donor',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='historicaldonation',
            name='donation_type',
            field=models.CharField(choices=[('ECOAPORTE', 'Bono Donación / Ecoaporte'), ('PERMANENT_SPONSOR', 'Padrino Permanente')], default='ECOAPORTE', max_length=32),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='donor_type',
            field=models.CharField(choices=[('PERSON', 'Persona natural'), ('FAMILY', 'Familia'), ('COMPANY', 'Empresa')], default='PERSON', max_length=16),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
