# Generated by Django 6.0.4 on 2026-05-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_donation_type_donor_donor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='category',
            field=models.CharField(choices=[('BRONZE', 'Bronce (Nivel 1)'), ('SILVER', 'Plata (Nivel 2)'), ('GOLD', 'Oro (Nivel 3)'), ('PLATINUM', 'Platino (Nivel 4)')], default='BRONZE', max_length=32),
        ),
        migrations.AddField(
            model_name='donor',
            name='marketing_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='payment_day',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='donor',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='category',
            field=models.CharField(choices=[('BRONZE', 'Bronce (Nivel 1)'), ('SILVER', 'Plata (Nivel 2)'), ('GOLD', 'Oro (Nivel 3)'), ('PLATINUM', 'Platino (Nivel 4)')], default='BRONZE', max_length=32),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='marketing_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='payment_day',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='historicaldonor',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
