# Generated by Django 6.0.4 on 2026-05-16 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('login_failed', 'Inicio de sesión fallido'), ('logout', 'Cierre de sesión'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('soft_delete', 'Eliminación lógica'), ('restore', 'Restauración'), ('export', 'Exportación')], db_index=True, max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
