# Generated by Django 6.0.4 on 2026-06-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_evidence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
