# Generated by Django 6.0.4 on 2026-06-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_managers_historicalblogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('publish_blogpost', 'Can publish blog post')], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
    ]
