# Generated by Django 6.0.4 on 2026-04-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Presupuesto')),
                ('monto_recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto recaudado')),
                ('estado', models.CharField(choices=[('planificacion', 'En planificación'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateField(blank=True, null=True, verbose_name='Fecha de vinculación')),
            ],
            options={
                'verbose_name': 'Beneficiario en proyecto',
                'verbose_name_plural': 'Beneficiarios en proyectos',
                'db_table': 'proyectos_beneficiarios',
            },
        ),
    ]
