# Generated by Django 6.0.4 on 2026-04-29 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Presupuesto')),
                ('monto_recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto recaudado')),
                ('estado', models.CharField(choices=[('planificacion', 'En planificación'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateField(blank=True, null=True, verbose_name='Fecha de vinculación')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Beneficiario en proyecto',
                'verbose_name_plural': 'Beneficiarios en proyectos',
                'db_table': 'proyectos_beneficiarios',
                'unique_together': {('proyecto', 'beneficiario')},
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='beneficiarios',
            field=models.ManyToManyField(related_name='proyectos', through='proyectos.ProyectoBeneficiario', to='beneficiarios.beneficiario', verbose_name='Beneficiarios'),
        ),
    ]
