# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='proyectobeneficiario',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiario'),
        ),
        migrations.AddField(
            model_name='proyectobeneficiario',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='beneficiarios',
            field=models.ManyToManyField(related_name='proyectos', through='proyectos.ProyectoBeneficiario', to='beneficiarios.beneficiario', verbose_name='Beneficiarios'),
        ),
        migrations.AlterUniqueTogether(
            name='proyectobeneficiario',
            unique_together={('proyecto', 'beneficiario')},
        ),
    ]
